[[build]]
builder = "NIXPACKS"
watchPatterns = ["**/*.php", "composer.json", "composer.lock"]

[[deploy]]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.environmentVariables]
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/database/database.sqlite"
